import pandas as pd

def get_rations_data():
    """
    Returns the First Strike Ration Menus 2012 data as a pandas DataFrame.
    This data is extracted from the rations1.gs file provided.
    """
    data = [
        ["1", "Entree", "Sandwich, Shelf Stable, Bacon Cheddar", 88, 327.36],
        ["1", "Entree", "Sandwich, Shelf Stable, Pepperoni", 70, 265.3],
        ["1", "Snack", "Pretzels, Sticks", 28, 103.88],
        ["1", "Snack", "Dessert Bar, Peanut Butter", 40, 231.6],
        ["1", "Snack", "Beef Snacks, Teriyaki", 26, 78.26],
        ["1", "Snack", "Beef Snacks, Barbecue", 26, 76.7],
        ["1", "Snack", "Filled Bakery, Filled French Toast", 99, 322.74],
        ["1", "Snack", "Nut and Fruit Mix, Sunflower Kernels and Infused Fruit", 56, 314.72],
        ["1", "Snack", "First Strike Bar, Mini, Chocolate", 35, 149.8],
        ["1", "Bread/Crax", "Snack Bread, Wheat", 57, 201.78],
        ["1", "Spread", "Cheese Spread, Cheddar with Jalapeno Peppers and Vitamin D", 42.75, 160.51],
        ["1", "Candy", "Caffeinated Gum, Cinnamon", 12.5, 50],
        ["1", "Beverage", "Chocolate Protein Drink", 70, 271.6],
        ["1", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["1", "Fruit", "Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced, Cinnamon", 125, 127.5],
        ["1", "Accessory Packet B", "Chewing Gum, Xylitol", 3.2, 2],
        ["2", "Entree", "Sandwich, Shelf Stable, Italian Style", 100, 319],
        ["2", "Entree", "Chicken Chunks, White", 196, 192.67],
        ["2", "Snack", "Toaster Pastry, Frosted Brown Sugar Cinnamon", 51, 204.09],
        ["2", "Snack", "Dessert Bar, Mocha", 40, 225.2],
        ["2", "Snack", "First Strike Bar, Mini, Apple-Cinnamon", 35, 150.15],
        ["2", "Snack", "Beef Snacks, Barbecue", 26, 76.7],
        ["2", "Snack", "Beef Snacks, Teriyaki", 26, 78.26],
        ["2", "Snack", "Nuts, Almonds, Smoked", 19, 120.46],
        ["2", "Bread/Crax", "Tortillas", 62, 222.58],
        ["2", "Bread/Crax", "Crackers, Plain", 38.6, 174.68],
        ["2", "Spread", "Peanut Butter, Smooth", 42.5, 266.05],
        ["2", "Candy", "Caffeinated Gum, Cinnamon", 12.5, 50],
        ["2", "Candy", "Caffeinated Gum, Peppermint", 15, 50],
        ["2", "Condiment", "Barbecue Sauce", 28.35, 49.33],
        ["2", "Condiment", "Hot Sauce, Extra Hot 4x", 4, 0],
        ["2", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["2", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["2", "Fruit", "Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced", 128, 143.36],
        ["2", "Fruit", "Dried Fruit, Cranberries", 56, 191.52],
        ["2", "Accessory Packet B", "Beverage Base, Sugar Free", 3.2, 11.3],
        ["2", "Accessory Packet B", "Chewing Gum, Xylitol", 3.2, 2],
        ["2", "Accessory Packet B", "Salt, Iodized", 4, 0],
        ["2", "Accessory Packet B", "Group Average - Accessory Packet B", 3.47, 5.65],
        ["3", "Entree", "Sandwich, Shelf Stable, Honey Barbecue Beef", 100, 285],
        ["3", "Entree", "Tuna, Chunk Light, Lemon Pepper", 128, 136.96],
        ["3", "Snack", "Pound Cake, Lemon Poppy Seed", 70, 298.9],
        ["3", "Snack", "Dessert Bar, Chocolate Banana Nut", 40, 236.8],
        ["3", "Snack", "First Strike Bar, Mini, Mocha", 35, 150.15],
        ["3", "Snack", "Toasted Corn Kernels, Plain", 57, 259.92],
        ["3", "Snack", "Nut and Fruit Mix, Sunflower Kernels and Infused Fruit", 56, 314.72],
        ["3", "Snack", "First Strike Bar, Mini, Cran-Raspberry", 35, 135.98],
        ["3", "Bread/Crax", "Tortillas", 62, 222.58],
        ["3", "Bread/Crax", "Crackers, Plain", 38.6, 174.68],
        ["3", "Spread", "Cheese Spread, Cheddar, Plain", 42.5, 167.03],
        ["3", "Candy", "Caffeinated Gum, Cinnamon", 12.5, 50],
        ["3", "Candy", "Caffeinated Mints FSR, Peppermint", 11, 30],
        ["3", "Condiment", "Mayonnaise, Fat Free", 28.35, 21.57],
        ["3", "Condiment", "Hot Sauce, Extra Hot 4x", 4, 0],
        ["3", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["3", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["3", "Fruit", "Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced", 128, 143.36],
        ["3", "Accessory Packet A", "Chewing Gum, Xylitol", 3.2, 2],
        ["3", "Accessory Packet A", "Coffee, Soluble, Freeze Dried", 1.7, 5.8],
        ["3", "Accessory Packet A", "Creamer, Non-Dairy, Dry", 4, 21],
        ["3", "Accessory Packet A", "Salt, Iodized", 4, 0],
        ["3", "Accessory Packet A", "Sugar", 4, 15],
        ["3", "Accessory Packet A", "Group Average - Accessory Packet A", 3.38, 10.2],
        ["4", "Entree", "Filled Wrap, Mexican Style Beef", 125, 361.25],
        ["4", "Entree", "Chicken Breast Fillets, Barbecue Sauce", 113, 138.99],
        ["4", "Snack", "Energy Gel, Mixed Berry", 60, 150],
        ["4", "Snack", "Filled Bakery, Cinnamon Bun", 100, 319],
        ["4", "Snack", "Dessert Bar, Peanut Butter", 40, 231.6],
        ["4", "Snack", "Filled Pretzels, Cheddar", 51, 232.56],
        ["4", "Snack", "First Strike Bar, Mini, Mocha", 35, 150.15],
        ["4", "Snack", "Beef Snacks, Cranberry, Nuggets", 43, 125.99],
        ["4", "Bread/Crax", "Snack Bread, Wheat", 57, 201.78],
        ["4", "Spread", "Cheese Spread, Cheddar with Jalapeno Peppers", 42.5, 162.78],
        ["4", "Candy", "Caffeinated Gum, Cinnamon", 12.5, 50],
        ["4", "Candy", "Caffeinated Gum, Cinnamon", 12.5, 50],
        ["4", "Condiment", "Hot Sauce, Extra Hot 4x", 4, 0],
        ["4", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["4", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["4", "Fruit", "Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced", 128, 143.36],
        ["4", "Fruit", "Dried Fruit, Raisins", 43, 144.91],
        ["4", "Accessory Packet A", "Chewing Gum, Xylitol", 3.2, 2],
        ["4", "Accessory Packet A", "Coffee, Soluble, Freeze Dried", 1.7, 5.8],
        ["4", "Accessory Packet A", "Creamer, Non-Dairy, Dry", 4, 21],
        ["4", "Accessory Packet A", "Salt, Iodized", 4, 0],
        ["4", "Accessory Packet A", "Sugar", 4, 15],
        ["4", "Accessory Packet A", "Group Average - Accessory Packet A", 3.38, 10.2],
        ["5", "Entree", "Sandwich, Shelf Stable, Honey Barbecue Chicken", 99.2, 293.63],
        ["5", "Entree", "Salmon, Pink, Mango Chipotle", 113, 123.17],
        ["5", "Snack", "Filled Bakery, Filled French Toast", 99, 322.74],
        ["5", "Snack", "Turkey Snacks, Smoked, Nuggets", 43, 126.85],
        ["5", "Snack", "First Strike Bar, Mini, Cran-Raspberry", 35, 135.98],
        ["5", "Snack", "Nut and Raisin Mix with Pan Coated Chocolate Disks", 66, 369.27],
        ["5", "Snack", "Toaster Pastry, Frosted Brown Sugar Cinnamon", 51, 204.09],
        ["5", "Snack", "Toasted Corn Kernels, Plain", 57, 259.92],
        ["5", "Snack", "Energy Gel, Mixed Berry", 60, 150],
        ["5", "Bread/Crax", "Crackers, Plain", 38.6, 174.68],
        ["5", "Spread", "Peanut Butter, Smooth", 42.5, 266.05],
        ["5", "Candy", "Caffeinated Mints FSR, Peppermint", 11, 30],
        ["5", "Beverage", "Chocolate Protein Drink", 70, 271.6],
        ["5", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["5", "Fruit", "Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced, Cinnamon", 125, 127.5],
        ["5", "Accessory Packet C", "Chewing Gum, Xylitol", 3.2, 2],
        ["5", "Accessory Packet C", "Salt, Iodized", 4, 0],
        ["5", "Accessory Packet C", "Group Average - Accessory Packet C", 3.6, 0],
        ["6", "Entree", "Filled Wrap, Barbecue Seasoned Pork", 125, 343.75],
        ["6", "Entree", "Chicken Breast Fillets, Garlic and Herb", 113, 120.91],
        ["6", "Snack", "Filled Bakery, Apple Turnover", 94, 294.22],
        ["6", "Snack", "Beef Snacks, Cranberry, Nuggets", 43, 125.99],
        ["6", "Snack", "Dessert Bar, Mocha", 40, 225.2],
        ["6", "Snack", "Caffeinated Chocolate Pudding", 125, 252.5],
        ["6", "Snack", "First Strike Bar, Mini, Apple-Cinnamon", 35, 150.15],
        ["6", "Snack", "Filled Pretzels, Cheddar", 51, 232.56],
        ["6", "Bread/Crax", "Bagel, Plain", 56.7, 163.3],
        ["6", "Spread", "Cheese Spread, Cheddar, Plain", 42.5, 167.03],
        ["6", "Candy", "Caffeinated Gum, Cinnamon", 12.5, 50],
        ["6", "Candy", "Caffeinated Gum, Peppermint", 15, 50],
        ["6", "Condiment", "Hot Sauce, Extra Hot 4x", 4, 0],
        ["6", "Beverage", "Dairyshake Powder, Strawberry Banana, Fortified, 70 grams", 70, 316.05],
        ["6", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["6", "Fruit", "Dried Fruit, Cranberries", 56, 191.52],
        ["6", "Accessory Packet C", "Chewing Gum, Xylitol", 3.2, 2],
        ["6", "Accessory Packet C", "Salt, Iodized", 4, 0],
        ["6", "Accessory Packet C", "Group Average - Accessory Packet C", 3.6, 0],
        ["7", "Entree", "Sandwich, Shelf Stable, Nacho Flavored Beef", 70.8, 247.8],
        ["7", "Entree", "Tuna, Chunk Light, Sweet and Spicy", 128, 147.2],
        ["7", "Snack", "Baked Snack Crackers, Hot and Spicy Cheese", 47, 236.41],
        ["7", "Snack", "Turkey Snacks, Smoked, Nuggets", 43, 126.85],
        ["7", "Snack", "First Strike Bar, Mini, Chocolate", 35, 149.8],
        ["7", "Snack", "Nut and Fruit Mix, Sunflower Kernels and Infused Fruit", 56, 314.72],
        ["7", "Snack", "First Strike Bar, Mini, Apple-Cinnamon", 35, 150.15],
        ["7", "Snack", "Filled Bakery, Blueberry Turnover", 88, 282.48],
        ["7", "Bread/Crax", "Crackers, Plain", 38.6, 174.68],
        ["7", "Bread/Crax", "Snack Bread, Wheat", 57, 201.78],
        ["7", "Spread", "Spread Soup Mix, Cheddar Potato with Bacon", 40, 257.2],
        ["7", "Candy", "Caffeinated Gum, Cinnamon", 12.5, 50],
        ["7", "Candy", "Caffeinated Gum, Cinnamon", 12.5, 50],
        ["7", "Condiment", "Mayonnaise, Fat Free", 28.35, 21.57],
        ["7", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["7", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["7", "Fruit", "Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced", 128, 143.36],
        ["7", "Accessory Packet A", "Chewing Gum, Xylitol", 3.2, 2],
        ["7", "Accessory Packet A", "Coffee, Soluble, Freeze Dried", 1.7, 5.8],
        ["7", "Accessory Packet A", "Creamer, Non-Dairy, Dry", 4, 21],
        ["7", "Accessory Packet A", "Salt, Iodized", 4, 0],
        ["7", "Accessory Packet A", "Sugar", 4, 15],
        ["7", "Accessory Packet A", "Group Average - Accessory Packet A", 3.38, 10.2],
        ["8", "Entree", "Sandwich, Shelf Stable, Honey Barbecue Chicken", 99.2, 293.63],
        ["8", "Entree", "Tuna, Albacore", 85, 84.58],
        ["8", "Snack", "Filled Bakery, Filled French Toast", 99, 322.74],
        ["8", "Snack", "Beef Snacks, Barbecue", 26, 76.7],
        ["8", "Snack", "Dessert Bar, Chocolate Banana Nut", 40, 236.8],
        ["8", "Snack", "First Strike Bar, Mini, Mocha", 35, 150.15],
        ["8", "Snack", "Nut and Raisin Mix with Pan Coated Chocolate Disks", 66, 369.27],
        ["8", "Snack", "Beef Snacks, Teriyaki", 26, 78.26],
        ["8", "Snack", "Filled Crackers", 48, 240],
        ["8", "Bread/Crax", "Bagel, Plain", 56.7, 163.3],
        ["8", "Candy", "Caffeinated Gum, Cinnamon", 12.5, 50],
        ["8", "Candy", "Caffeinated Gum, Peppermint", 15, 50],
        ["8", "Condiment", "Mayonnaise, Fat Free", 28.35, 21.57],
        ["8", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["8", "Beverage", "Dairyshake Powder, Vanilla, Fortified 70 grams", 70, 324.8],
        ["8", "Fruit", "Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced, Cinnamon", 125, 127.5],
        ["8", "Accessory Packet A", "Chewing Gum, Xylitol", 3.2, 2],
        ["8", "Accessory Packet A", "Coffee, Soluble, Freeze Dried", 1.7, 5.8],
        ["8", "Accessory Packet A", "Creamer, Non-Dairy, Dry", 4, 21],
        ["8", "Accessory Packet A", "Salt, Iodized", 4, 0],
        ["8", "Accessory Packet A", "Sugar", 4, 15],
        ["8", "Accessory Packet A", "Group Average - Accessory Packet A", 3.38, 10.2],
        ["9", "Entree", "Sandwich, Shelf Stable, Italian Style", 100, 319],
        ["9", "Entree", "Chicken Breast Fillets, Garlic and Herb", 113, 120.91],
        ["9", "Snack", "Toasted Corn Kernels, Plain", 57, 259.92],
        ["9", "Snack", "Beef Snacks, Cranberry, Nuggets", 43, 125.99],
        ["9", "Snack", "Filled Bakery, Cinnamon Bun", 100, 319],
        ["9", "Snack", "First Strike Bar, Mini, Cran-Raspberry", 35, 135.98],
        ["9", "Snack", "Caffeinated Chocolate Pudding", 125, 252.5],
        ["9", "Bread/Crax", "Tortillas", 62, 222.58],
        ["9", "Bread/Crax", "Crackers, Plain", 38.6, 174.68],
        ["9", "Spread", "Spread Soup Mix, Cheddar Potato with Bacon", 40, 257.2],
        ["9", "Candy", "Caffeinated Mints FSR, Peppermint", 11, 30],
        ["9", "Beverage", "Dairyshake Powder, Vanilla, Fortified 70 grams", 70, 324.8],
        ["9", "Beverage", "Beverage Base, Ergo, Formulation E", 47, 171.08],
        ["9", "Fruit", "Dried Fruit, Raisins", 43, 144.91],
        ["9", "Accessory Packet B", "Beverage Base, Sugar Free", 3.2, 11.3],
        ["9", "Accessory Packet B", "Chewing Gum, Xylitol", 3.2, 2],
        ["9", "Accessory Packet B", "Salt, Iodized", 4, 0],
        ["9", "Accessory Packet B", "Group Average - Accessory Packet B", 3.47, 5.65],
    ]
    
    columns = ["Menu", "Type", "Item", "Grams", "Calories"]
    df = pd.DataFrame(data, columns=columns)
    df['Calories per Gram'] = df['Calories'] / df['Grams']
    return df
