function doGet() {  
  var data = Charts.newDataTable()
      .addColumn(Charts.ColumnType.STRING, "Menu")
      .addColumn(Charts.ColumnType.STRING, "Type")
      .addColumn(Charts.ColumnType.STRING, "Item")
      .addColumn(Charts.ColumnType.NUMBER, "Grams")
      .addColumn(Charts.ColumnType.NUMBER, "Calories")
.addRow(["1","Entree","Sandwich, Shelf Stable, Bacon Cheddar",88,327.36])
.addRow(["1","Entree","Sandwich, Shelf Stable, Pepperoni",70,265.3])
.addRow(["1","Snack","Pretzels, Sticks",28,103.88])
.addRow(["1","Snack","Dessert Bar, Peanut Butter",40,231.6])
.addRow(["1","Snack","Beef Snacks, Teriyaki",26,78.26])
.addRow(["1","Snack","Beef Snacks, Barbecue",26,76.7])
.addRow(["1","Snack","Filled Bakery, Filled French Toast",99,322.74])
.addRow(["1","Snack","Nut and Fruit Mix, Sunflower Kernels and Infused Fruit",56,314.72])
.addRow(["1","Snack","First Strike Bar, Mini, Chocolate",35,149.8])
.addRow(["1","Bread/Crax","Snack Bread, Wheat",57,201.78])
.addRow(["1","Spread","Cheese Spread, Cheddar with Jalapeno Peppers and Vitamin D",42.75,160.51])
.addRow(["1","Candy","Caffeinated Gum, Cinnamon",12.5,50])
.addRow(["1","Beverage","Chocolate Protein Drink",70,271.6])
.addRow(["1","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["1","Fruit","Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced, Cinnamon",125,127.5])
.addRow(["1","Accessory Pkt","Chewing Gum, Xylitol",3.2,2])
.addRow(["2","Entree","Sandwich, Shelf Stable, Italian Style",100,319])
.addRow(["2","Entree","Chicken Chunks, White",196,192.67])
.addRow(["2","Snack","Toaster Pastry, Frosted Brown Sugar Cinnamon",51,204.09])
.addRow(["2","Snack","Dessert Bar, Mocha",40,225.2])
.addRow(["2","Snack","First Strike Bar, Mini, Apple-Cinnamon",35,150.15])
.addRow(["2","Snack","Beef Snacks, Barbecue",26,76.7])
.addRow(["2","Snack","Beef Snacks, Teriyaki",26,78.26])
.addRow(["2","Snack","Nuts, Almonds, Smoked",19,120.46])
.addRow(["2","Bread/Crax","Tortillas",62,222.58])
.addRow(["2","Bread/Crax","Crackers, Plain",38.6,174.68])
.addRow(["2","Spread","Peanut Butter, Smooth",42.5,266.05])
.addRow(["2","Candy","Caffeinated Gum, Cinnamon",12.5,50])
.addRow(["2","Candy","Caffeinated Gum, Peppermint",15,50])
.addRow(["2","Condiment","Barbecue Sauce",28.35,49.33])
.addRow(["2","Condiment","Hot Sauce, Extra Hot 4x",4,0])
.addRow(["2","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["2","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["2","Fruit","Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced",128,143.36])
.addRow(["2","Fruit","Dried Fruit, Cranberries",56,191.52])
.addRow(["2","FSR 2012 Accessory Packet B","Beverage Base, Sugar Free",3.2,11.3])
.addRow(["2","FSR 2012 Accessory Packet B","Chewing Gum, Xylitol",3.2,2])
.addRow(["2","FSR 2012 Accessory Packet B","Salt, Iodized",4,0])
.addRow(["2","FSR 2012 Accessory Packet B","Group Average - FSR 2012 Accessory Packet B",3.47,5.65])
.addRow(["3","Entree","Sandwich, Shelf Stable, Honey Barbecue Beef",100,285])
.addRow(["3","Entree","Tuna, Chunk Light, Lemon Pepper",128,136.96])
.addRow(["3","Snack","Pound Cake, Lemon Poppy Seed",70,298.9])
.addRow(["3","Snack","Dessert Bar, Chocolate Banana Nut",40,236.8])
.addRow(["3","Snack","First Strike Bar, Mini, Mocha",35,150.15])
.addRow(["3","Snack","Toasted Corn Kernels, Plain",57,259.92])
.addRow(["3","Snack","Nut and Fruit Mix, Sunflower Kernels and Infused Fruit",56,314.72])
.addRow(["3","Snack","First Strike Bar, Mini, Cran-Raspberry",35,135.98])
.addRow(["3","Bread/Crax","Tortillas",62,222.58])
.addRow(["3","Bread/Crax","Crackers, Plain",38.6,174.68])
.addRow(["3","Spread","Cheese Spread, Cheddar, Plain",42.5,167.03])
.addRow(["3","Candy","Caffeinated Gum, Cinnamon",12.5,50])
.addRow(["3","Candy","Caffeinated Mints FSR, Peppermint",11,30])
.addRow(["3","Condiment","Mayonnaise, Fat Free",28.35,21.57])
.addRow(["3","Condiment","Hot Sauce, Extra Hot 4x",4,0])
.addRow(["3","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["3","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["3","Fruit","Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced",128,143.36])
.addRow(["3","FSR 2012 Accessory Packet A","Chewing Gum, Xylitol",3.2,2])
.addRow(["3","FSR 2012 Accessory Packet A","Coffee, Soluble, Freeze Dried",1.7,5.8])
.addRow(["3","FSR 2012 Accessory Packet A","Creamer, Non-Dairy, Dry",4,21])
.addRow(["3","FSR 2012 Accessory Packet A","Salt, Iodized",4,0])
.addRow(["3","FSR 2012 Accessory Packet A","Sugar",4,15])
.addRow(["3","FSR 2012 Accessory Packet A","Group Average - FSR 2012 Accessory Packet A",3.38,10.2])
.addRow(["4","Entree","Filled Wrap, Mexican Style Beef",125,361.25])
.addRow(["4","Entree","Chicken Breast Fillets, Barbecue Sauce",113,138.99])
.addRow(["4","Snack","Energy Gel, Mixed Berry",60,150])
.addRow(["4","Snack","Filled Bakery, Cinnamon Bun",100,319])
.addRow(["4","Snack","Dessert Bar, Peanut Butter",40,231.6])
.addRow(["4","Snack","Filled Pretzels, Cheddar",51,232.56])
.addRow(["4","Snack","First Strike Bar, Mini, Mocha",35,150.15])
.addRow(["4","Snack","Beef Snacks, Cranberry, Nuggets",43,125.99])
.addRow(["4","Bread/Crax","Snack Bread, Wheat",57,201.78])
.addRow(["4","Spread","Cheese Spread, Cheddar with Jalapeno Peppers",42.5,162.78])
.addRow(["4","Candy","Caffeinated Gum, Cinnamon",12.5,50])
.addRow(["4","Candy","Caffeinated Gum, Cinnamon",12.5,50])
.addRow(["4","Condiment","Hot Sauce, Extra Hot 4x",4,0])
.addRow(["4","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["4","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["4","Fruit","Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced",128,143.36])
.addRow(["4","Fruit","Dried Fruit, Raisins",43,144.91])
.addRow(["4","FSR 2012 Accessory Packet A","Chewing Gum, Xylitol",3.2,2])
.addRow(["4","FSR 2012 Accessory Packet A","Coffee, Soluble, Freeze Dried",1.7,5.8])
.addRow(["4","FSR 2012 Accessory Packet A","Creamer, Non-Dairy, Dry",4,21])
.addRow(["4","FSR 2012 Accessory Packet A","Salt, Iodized",4,0])
.addRow(["4","FSR 2012 Accessory Packet A","Sugar",4,15])
.addRow(["4","FSR 2012 Accessory Packet A","Group Average - FSR 2012 Accessory Packet A",3.38,10.2])
.addRow(["5","Entree","Sandwich, Shelf Stable, Honey Barbecue Chicken",99.2,293.63])
.addRow(["5","Entree","Salmon, Pink, Mango Chipotle",113,123.17])
.addRow(["5","Snack","Filled Bakery, Filled French Toast",99,322.74])
.addRow(["5","Snack","Turkey Snacks, Smoked, Nuggets",43,126.85])
.addRow(["5","Snack","First Strike Bar, Mini, Cran-Raspberry",35,135.98])
.addRow(["5","Snack","Nut and Raisin Mix with Pan Coated Chocolate Disks",66,369.27])
.addRow(["5","Snack","Toaster Pastry, Frosted Brown Sugar Cinnamon",51,204.09])
.addRow(["5","Snack","Toasted Corn Kernels, Plain",57,259.92])
.addRow(["5","Snack","Energy Gel, Mixed Berry",60,150])
.addRow(["5","Bread/Crax","Crackers, Plain",38.6,174.68])
.addRow(["5","Spread","Peanut Butter, Smooth",42.5,266.05])
.addRow(["5","Candy","Caffeinated Mints FSR, Peppermint",11,30])
.addRow(["5","Beverage","Chocolate Protein Drink",70,271.6])
.addRow(["5","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["5","Fruit","Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced, Cinnamon",125,127.5])
.addRow(["5","FSR 2012 Accessory Packet C","Chewing Gum, Xylitol",3.2,2])
.addRow(["5","FSR 2012 Accessory Packet C","Salt, Iodized",4,0])
.addRow(["5","FSR 2012 Accessory Packet C","Group Average - FSR 2012 Accessory Packet C",3.6,0])
.addRow(["6","Entree","Filled Wrap, Barbecue Seasoned Pork",125,343.75])
.addRow(["6","Entree","Chicken Breast Fillets, Garlic and Herb",113,120.91])
.addRow(["6","Snack","Filled Bakery, Apple Turnover",94,294.22])
.addRow(["6","Snack","Beef Snacks, Cranberry, Nuggets",43,125.99])
.addRow(["6","Snack","Dessert Bar, Mocha",40,225.2])
.addRow(["6","Snack","Caffeinated Chocolate Pudding",125,252.5])
.addRow(["6","Snack","First Strike Bar, Mini, Apple-Cinnamon",35,150.15])
.addRow(["6","Snack","Filled Pretzels, Cheddar",51,232.56])
.addRow(["6","Bread/Crax","Bagel, Plain",56.7,163.3])
.addRow(["6","Spread","Cheese Spread, Cheddar, Plain",42.5,167.03])
.addRow(["6","Candy","Caffeinated Gum, Cinnamon",12.5,50])
.addRow(["6","Candy","Caffeinated Gum, Peppermint",15,50])
.addRow(["6","Condiment","Hot Sauce, Extra Hot 4x",4,0])
.addRow(["6","Beverage","Dairyshake Powder, Strawberry Banana, Fortified, 70 grams",70,316.05])
.addRow(["6","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["6","Fruit","Dried Fruit, Cranberries",56,191.52])
.addRow(["6","FSR 2012 Accessory Packet C","Chewing Gum, Xylitol",3.2,2])
.addRow(["6","FSR 2012 Accessory Packet C","Salt, Iodized",4,0])
.addRow(["6","FSR 2012 Accessory Packet C","Group Average - FSR 2012 Accessory Packet C",3.6,0])
.addRow(["7","Entree","Sandwich, Shelf Stable, Nacho Flavored Beef",70.8,247.8])
.addRow(["7","Entree","Tuna, Chunk Light, Sweet and Spicy",128,147.2])
.addRow(["7","Snack","Baked Snack Crackers, Hot and Spicy Cheese",47,236.41])
.addRow(["7","Snack","Turkey Snacks, Smoked, Nuggets",43,126.85])
.addRow(["7","Snack","First Strike Bar, Mini, Chocolate",35,149.8])
.addRow(["7","Snack","Nut and Fruit Mix, Sunflower Kernels and Infused Fruit",56,314.72])
.addRow(["7","Snack","First Strike Bar, Mini, Apple-Cinnamon",35,150.15])
.addRow(["7","Snack","Filled Bakery, Blueberry Turnover",88,282.48])
.addRow(["7","Bread/Crax","Crackers, Plain",38.6,174.68])
.addRow(["7","Bread/Crax","Snack Bread, Wheat",57,201.78])
.addRow(["7","Spread","Spread Soup Mix, Cheddar Potato with Bacon",40,257.2])
.addRow(["7","Candy","Caffeinated Gum, Cinnamon",12.5,50])
.addRow(["7","Candy","Caffeinated Gum, Cinnamon",12.5,50])
.addRow(["7","Condiment","Mayonnaise, Fat Free",28.35,21.57])
.addRow(["7","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["7","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["7","Fruit","Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced",128,143.36])
.addRow(["7","FSR 2012 Accessory Packet A","Chewing Gum, Xylitol",3.2,2])
.addRow(["7","FSR 2012 Accessory Packet A","Coffee, Soluble, Freeze Dried",1.7,5.8])
.addRow(["7","FSR 2012 Accessory Packet A","Creamer, Non-Dairy, Dry",4,21])
.addRow(["7","FSR 2012 Accessory Packet A","Salt, Iodized",4,0])
.addRow(["7","FSR 2012 Accessory Packet A","Sugar",4,15])
.addRow(["7","FSR 2012 Accessory Packet A","Group Average - FSR 2012 Accessory Packet A",3.38,10.2])
.addRow(["8","Entree","Sandwich, Shelf Stable, Honey Barbecue Chicken",99.2,293.63])
.addRow(["8","Entree","Tuna, Albacore",85,84.58])
.addRow(["8","Snack","Filled Bakery, Filled French Toast",99,322.74])
.addRow(["8","Snack","Beef Snacks, Barbecue",26,76.7])
.addRow(["8","Snack","Dessert Bar, Chocolate Banana Nut",40,236.8])
.addRow(["8","Snack","First Strike Bar, Mini, Mocha",35,150.15])
.addRow(["8","Snack","Nut and Raisin Mix with Pan Coated Chocolate Disks",66,369.27])
.addRow(["8","Snack","Beef Snacks, Teriyaki",26,78.26])
.addRow(["8","Snack","Filled Crackers",48,240])
.addRow(["8","Bread/Crax","Bagel, Plain",56.7,163.3])
.addRow(["8","Candy","Caffeinated Gum, Cinnamon",12.5,50])
.addRow(["8","Candy","Caffeinated Gum, Peppermint",15,50])
.addRow(["8","Condiment","Mayonnaise, Fat Free",28.35,21.57])
.addRow(["8","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["8","Beverage","Dairyshake Powder, Vanilla, Fortified 70 grams",70,324.8])
.addRow(["8","Fruit","Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced, Cinnamon",125,127.5])
.addRow(["8","FSR 2012 Accessory Packet A","Chewing Gum, Xylitol",3.2,2])
.addRow(["8","FSR 2012 Accessory Packet A","Coffee, Soluble, Freeze Dried",1.7,5.8])
.addRow(["8","FSR 2012 Accessory Packet A","Creamer, Non-Dairy, Dry",4,21])
.addRow(["8","FSR 2012 Accessory Packet A","Salt, Iodized",4,0])
.addRow(["8","FSR 2012 Accessory Packet A","Sugar",4,15])
.addRow(["8","FSR 2012 Accessory Packet A","Group Average - FSR 2012 Accessory Packet A",3.38,10.2])
.addRow(["9","Entree","Sandwich, Shelf Stable, Italian Style",100,319])
.addRow(["9","Entree","Chicken Breast Fillets, Garlic and Herb",113,120.91])
.addRow(["9","Snack","Toasted Corn Kernels, Plain",57,259.92])
.addRow(["9","Snack","Beef Snacks, Cranberry, Nuggets",43,125.99])
.addRow(["9","Snack","Filled Bakery, Cinnamon Bun",100,319])
.addRow(["9","Snack","First Strike Bar, Mini, Cran-Raspberry",35,135.98])
.addRow(["9","Snack","Caffeinated Chocolate Pudding",125,252.5])
.addRow(["9","Bread/Crax","Tortillas",62,222.58])
.addRow(["9","Bread/Crax","Crackers, Plain",38.6,174.68])
.addRow(["9","Spread","Spread Soup Mix, Cheddar Potato with Bacon",40,257.2])
.addRow(["9","Candy","Caffeinated Mints FSR, Peppermint",11,30])
.addRow(["9","Beverage","Dairyshake Powder, Vanilla, Fortified 70 grams",70,324.8])
.addRow(["9","Beverage","Beverage Base, Ergo, Formulation E",47,171.08])
.addRow(["9","Fruit","Dried Fruit, Raisins",43,144.91])
.addRow(["9","FSR 2012 Accessory Packet B","Beverage Base, Sugar Free",3.2,11.3])
.addRow(["9","FSR 2012 Accessory Packet B","Chewing Gum, Xylitol",3.2,2])
.addRow(["9","FSR 2012 Accessory Packet B","Salt, Iodized",4,0])
.addRow(["9","FSR 2012 Accessory Packet B","Group Average - FSR 2012 Accessory Packet B",3.47,5.65])

      .build();

  var GramsFilter = Charts.newNumberRangeFilter()
      .setFilterColumnLabel("Grams")
      .build();
  
   var CaloriesFilter = Charts.newNumberRangeFilter()
      .setFilterColumnLabel("Calories")
      .build();

  var TypeFilter = Charts.newCategoryFilter()
      .setFilterColumnLabel("Type")
      .setCaption("Type of Item")
      .build();  

  var MenuFilter = Charts.newCategoryFilter()
      .setFilterColumnLabel("Menu")
      .setCaption("Menu Number")
      .build();
  
    var Chart1 = Charts.newBarChart()

      .setOption('animation.duration', 500)
      .setOption('legend', {position: 'bottom', textStyle: {color: 'black', fontSize: 10}})
      .setColors(["red"])
      .setTitle('Item\'s Calories')
      .setDataViewDefinition(Charts.newDataViewDefinition()
                            .setColumns([2,4]))
      .build();
  
      var Chart2 = Charts.newBarChart()
      .setOption('animation.duration', 500)
      .setOption('legend', {position: 'bottom', textStyle: {color: 'black', fontSize: 10}})
      .setColors(["blue"])
      .setTitle('Items\' Weight in Grams')
      .setDataViewDefinition(Charts.newDataViewDefinition()
                            .setColumns([2,3]))
      .build();
    var coolChart = Charts.newScatterChart()
      .setDataViewDefinition(Charts.newDataViewDefinition()
                            .setColumns([3,4]))
      .setXAxisTitle('Grams')
      .setYAxisTitle('Calories')
      .setColors(["blue"])
      .setTitle("Weight in Grams vs Calories")
    
 .setOption('legend', {position: 'bottom', textStyle: {color: 'black', fontSize: 10}})
      .build();

  var tableChart = Charts.newTableChart()
      .build();

  var dashboard = Charts.newDashboardPanel()
      .setDataTable(data)
      .bind([MenuFilter, GramsFilter, TypeFilter, CaloriesFilter], [Chart1, Chart2, tableChart, coolChart])
      .build();

  var uiApp = UiApp.createApplication();

  uiApp.add(uiApp.createHTML("<div style=\"text-align:center;width:400px\"><H1>Rations Optimizer</H1><H2>First Strike Ration Menus 2012</H2></div>"));

  dashboard.add(uiApp.createVerticalPanel()
                .setTitle('Items\' Calories vs Grams')  
                .setSpacing(-30)
                .add(MenuFilter)
                .add(TypeFilter)
                .add(CaloriesFilter)
                .add(GramsFilter)           
                .add(Chart1)
                .add(Chart2)
                .add(coolChart)
                .add(tableChart) 
                    );

  uiApp.add(dashboard);
  uiApp.add(uiApp.createHTML("<div style=\"text-align:center;width:400px;font-size:80%\"><br>By Eric Boehlke - truevis.com</div>"));
  return uiApp;
}
